language: php
php:
    - 5.6

before_script:
    - composer self-update
    - composer install
    - composer global require "laravel/installer"
    - composer create-project --prefer-dist laravel/laravel tmp
    - rsync -a tmp/ . --exclude "tests" --exclude "vendor" --exclude "*.xml" --exclude "*.json" --exclude "*.lock" --exclude "*.md"

script:
    - vendor/bin/phpunit
