language: php
php:
    - 5.6

install:
    - composer self-update
    - travis_retry composer install --no-interaction

before_script:
    - travis_retry git clone -b 5.4 --single-branch --depth=1 https://github.com/laravel/laravel.git tmp/
    - sleep 3
    - cp -r tmp/app tmp/bootstrap tmp/config tmp/routes tmp/storage tmp/artisan .

script:
    - vendor/bin/phpunit
