language: php
php:
    - 5.6

before_script:
    - composer self-update
    - composer install
    - composer create-project --prefer-dist laravel/laravel tmp
    - cp -rf tmp/app tmp/bootstrap tmp/config tmp/database tmp/public tmp/resources tmp/routes tmp/storage tmp/.env tmp/artisan tmp/server.php tmp/webpack.mix.js .

script:
    - vendor/bin/phpunit
